import Head from "next/head";

export default function Home() {
  return (
    <div className='h-screen w-full bg-gradient-to-br from-astro-blue via-astro-pink to-astro-red'>
      <Head>
        <title>Astroneir Design</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-blue-500'>HELLO</h1>

      <h1 className='text-5xl font-bold'>TEST</h1>
    </div>
  );
}
